version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: twitter_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - twitter_network

  fastapi:
    build: .
    container_name: twitter_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://admin:password123@rabbitmq:5672/
      - DATABASE_URL=sqlite:///./twitter_automation.db
    volumes:
      - ./data:/app/data
    networks:
      - twitter_network

volumes:
  rabbitmq_data:

networks:
  twitter_network:
    driver: bridge
